# Generated by Django 3.1 on 2020-08-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200810_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user_a',
            new_name='user_a_followed_by_b',
        ),
    ]
