# Generated by Django 3.1 on 2020-08-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200810_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user_a_followed_by_b', 'user_b_follows_a')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('like_post_id', 'like_user')},
        ),
    ]
