# Generated by Django 3.1 on 2020-08-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200810_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_post_id',
            new_name='like_post',
        ),
    ]
