# Generated by Django 3.1 on 2020-09-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200811_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/profile_images'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('like_post_id', 'like_user')},
        ),
    ]
