# Generated by Django 3.0.8 on 2020-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200709_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='listing',
            name='open_status',
            field=models.BooleanField(default=True),
        ),
    ]
