# Generated by Django 3.0.8 on 2020-07-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200709_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='max_bid',
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='users_watching', to='auctions.Listing'),
        ),
    ]
