# Generated by Django 3.0.8 on 2020-07-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200709_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AUTO', 'Automotive'), ('EL', 'Electronics'), ('ART', 'Arts'), ('SPT', 'Sports'), ('FSH', 'Fashion'), ('HME', 'Home'), ('RE', 'Real Estate'), ('PET', 'Pets'), ('IND', 'Industry'), ('KID', 'Kids')], max_length=24),
        ),
    ]
