# Generated by Django 3.0.8 on 2020-07-10 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200710_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing')),
            ],
        ),
    ]
