# Generated by Django 3.0.8 on 2020-07-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_current_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Current_Bid',
        ),
    ]
