# Generated by Django 3.0.8 on 2020-07-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_winners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Winners',
            new_name='Winner',
        ),
    ]
